site_name: Commentaires
site_url: https://denisshragin.github.io/chemistry_comments/
nav:
  - Métaux: 'index.md'
  - Organique: 'organique.md'
  - Inorganique: 'inorganique.md'
  - Inter-paramètres: 'inter_param.md'

theme: 
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - content.code.copy

  palette:
    primary: 

copyright: Copyright &copy; 2025  Denis Shragin

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true